### ISSUE TITLE
Status Tokens for TOA

### ISSUE THREAD

**Issue by solomojb** [any2cards/worldhaven#10]
Hey,

  Just wondering if you have a hi res image for some of the effects in CS/TOA.

  I am looking for Chill, Empower, Enfeeble and Crystalize. Note: not status tokens, but actually images that appears say on items or abilities)

Thanks,

Jim

**Comment by any2cards** [comment]
All of the assets I was provided for Tokens (both CS and TOA) were of the 300 DPI format and are included in the file repository (https://www.thecrimsonscales.com/files). Empower, Enfeeble, and Crystalize are not in there.  I have reached out to the creator to see if they have 1200 DPI versions, as well those identified above.

**Comment by any2cards** [comment]
I have discovered that there aren't really images per se for these things (Empower, Enfeeble, etc.).  They are integrated into individual assets.  As for Chill and Crystalize, those tokens already exist within the assets.
