### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by JacobBraxley** [any2cards/worldhaven#13]
Hi,

I believe worldhaven/images/art/frosthaven/monster-images/fh-fissure-in-the-deep.png  should be renamed to
fh-fracture-of-the-deep based on the images/monster-stat-cards/frosthaven/fh-fracture-of-the-deep card.

**Comment by any2cards** [comment]
Jacob ... thank you for pointing this out.  The funny thing is, Cephalofair's own assets had it labeled Fissure In The Deep.  That must have been the original name.  LOL.  I went ahead and changed it, and have pushed the changes.  They should show up in about 15 minutes.  Once again, thank you !
