### ISSUE TITLE
Are there higher resolution images available for the various frosthaven stickers?

### ISSUE THREAD

**Issue by gudyfr** [any2cards/worldhaven#15]
and as a side question, do you intend on cutting them out as individual stickers like you did for Gloomhaven ? I'm happy to help with that task.

**Comment by any2cards** [comment]
In order to shrink the size of the repo, I have had to remove all of the orig high resolution images of all assets.  As for the cutouts, those were supplied within the Gloomhaven assets, but not within the Frosthaven assets ... as such, I did not bother to make individual cuouts.

**Comment by any2cards** [comment]
Your post got me to thinking, and I actually double checked and found that I do have assets for the individual location stickers.  I will work on getting those generated.  I will also be working on a separate personal Dropbox location for the high resolution assets.

**Comment by gudyfr** [comment]
Thank you so much !

**Comment by any2cards** [comment]
I haven't forgotten about this.  I am actively working on it, amongst dealing with some medical issues.  About 25% done.  Lots of stickers to generate !

**Comment by gudyfr** [comment]
Thanks a lot. Happy to help if that's possible. Hope you get better soon.

**Comment by any2cards** [comment]
Gudyfr: Please send me an e-mail (any2cards@yahoo.com).
