### ISSUE TITLE
Status / Licensing?

### ISSUE THREAD

**Issue by michaelmcleodnz** [any2cards/worldhaven#20]
This is a fantastic resource for looking up information or for making 3rd-party apps, and I presume it must be endorsed by Cephalofair to a degree because I don't see how else you can get such high quality die-line and no-die-line versions of so many assets, but I can't find any information anywhere about how these images are sourced (which I'd be interested in purely for curiosity's sake), or what kind of permission one would need from Cephalofair to use them in other projects (which I'd be interested in for the sake of making projects). I know the files for creation have been released under CC-BY-NC-SA 4.0, but they don't contain the actual scenario/plot/character details that are found here.

Would it be possible to include a small blurb in the README explaining, say, "this is unofficial, the images are from [a playtester / the TTS mod], they are used [with Cephalofair's blessing / with the understanding that they were sourced from somewhere publically available], but if you want to use them in other projects you'd best ask Cephalofair", or whatever the case may be?

**Comment by any2cards** [comment]
I spoke with Isaac this morning.  He is working with his legal department to determine how and when any general access to assets will occur.  In the meantime, he has requested that I add a License Terms to my GitHub repository specifying that the assets are only to be used by me and my tools, and that they should not be utilized for other purposes.  I am working with them on the text to be added.  Thank you for you concerns/interest.
