### ISSUE TITLE
Mapping between characters and their cards.

### ISSUE THREAD

**Issue by phronmophobic** [any2cards/worldhaven#21]
`character-ability-cards.js` lists all the cards and some of their attributes. Other than looking at the "image" attribute, it doesn't seem like there's any link to the character the card belongs to. As an example:
```
    {
    "name": "toxic bolt",
    "points": 585,
    "expansion": "Gloomhaven",
    "image": "character-ability-cards/gloomhaven/TI/gh-toxic-bolt.png",
    "xws": "toxicbolt",
    "level": "1",
    "initiative": "18",
    "cardno": "041"
  }
```
None of attributes directly reference the character's "xws" or "name" attribute from `character-mats.js`.

Would you be interested in a pull request that added a "character_xws" attribute to each card?

Thanks!

**Comment by phronmophobic** [comment]
On a related note, "Crashing Tide" is the only xws that has a space in it.

**Comment by any2cards** [comment]
I am processing a bunch of similar things at the moment.  What specifically are you looking for?  In other words, tell me the card type (in this case I assume the character-ability-cards) and tell me what entry you want to see.  Give me an example.  Thanks.

**Comment by any2cards** [comment]
> On a related note, "Crashing Tide" is the only xws that has a space in it.

Within which data JS file does this exist?

**Comment by phronmophobic** [comment]
> I am processing a bunch of similar things at the moment. What specifically are you looking for? In other words, tell me the card type (in this case I assume the character-ability-cards) and tell me what entry you want to see. Give me an example. 

Sure. The proposal is to add a `character_xws` property to every card in character-ability-cards. As an example, the toxic bolt card from https://github.com/any2cards/worldhaven/blob/master/data/character-ability-cards.js#L5852 would go from:
```
    {
    "name": "toxic bolt",
    "points": 585,
    "expansion": "Gloomhaven",
    "image": "character-ability-cards/gloomhaven/TI/gh-toxic-bolt.png",
    "xws": "toxicbolt",
    "level": "1",
    "initiative": "18",
    "cardno": "041"
  }
```
to:
```
    {
    "name": "toxic bolt",
    "points": 585,
    "expansion": "Gloomhaven",
    "image": "character-ability-cards/gloomhaven/TI/gh-toxic-bolt.png",
    "xws": "toxicbolt",
    "level": "1",
    "initiative": "18",
    "cardno": "041",
    "character_xws": "tinkerer"
  }
```
---- 



>> On a related note, "Crashing Tide" is the only xws that has a space in it.

> Within which data JS file does this exist?

https://github.com/any2cards/worldhaven/blob/master/data/character-mats.js#L469


Thanks!

**Comment by any2cards** [comment]
The character mat entry for Crashing Tide has been fixed.  Thank you for pointing this out.

A new character-xws field has been added for all of the entries within the character-abilities-card.js file.

**Comment by phronmophobic** [comment]
Awesome!

**Comment by alexzhaohong** [comment]
Frosthaven's Snowdancer's character-xws field is incorrectly labeled as 'shadowdancer'

**Comment by any2cards** [comment]
This has been fixed.
