### ISSUE TITLE
WAV not working on BGG

### ISSUE THREAD

**Issue by StaffanBaloo** [any2cards/worldhaven#23]
When reading Frosthaven forums on BGG, the Worldhaven Asset Viewer doesn't work. It works on the main forum page (the list of threads, https://boardgamegeek.com/boardgame/295770/frosthaven/forums/0 ), but not when reading the actual threads (e.g. https://boardgamegeek.com/thread/3036977/anybody-been-using-these-persistentpermanent-abili ). I hypothesize that this is because the plugin is set to work on *://*.boardgamegeek.com/*, but there is no initial period in the URL. That doesn't explain why it works on the thread list though.

**Comment by any2cards** [comment]
It actually does work, but unfortunately, not all the time.  It has to do with how BGG redesigned their web pages over a year ago.  They are not honoring the run_at document_idle setting. At least they are doing so inconsistently.  For example, if I go to your link above, it works just fine for me most of the time.  And then it doesn't work.  Usually, pressing F5 to refresh the page can result it in working.  Unfortunately, this is a known issue, and nothing I can do on my end to fix it.  BGG is the only web site that has this issue, and it didn't exist prior to their website redesign.  I would suggest trying the F5 to refresh the page to see if it helps.

**Comment by any2cards** [comment]
A new version of the WAV (2.5.1) has been posted which resolves all of these issues.
