### ISSUE TITLE
Realm of Endless Frost (Scenario 21) - Not displaying

### ISSUE THREAD

**Issue by fifguy85** [any2cards/worldhaven#28]
Looks like a scenario title isn't registering in the WAV: "Realm of Endless Frost".  Here's a BGG page with both the title and scenario # formatting for reference: https://boardgamegeek.com/blogpost/145873/available-scenarios-1127 

Would it be possible to also include a section for Scenario names on the test viewer page (https://any2cards.github.io/worldhaven/) in the Spoiler section?

**Comment by any2cards** [comment]
I am pushing a fix for Realm of Endless Frost as I type this.  I had inadvertently added the word "the" before "Endless".

Scenario names already have a section on the test viewer page under everything spoiled.  It is located under Art.

I will post a follow up here once the update has been successfully posted.

**Comment by any2cards** [comment]
Fix has been posted and confirmed.
