### ISSUE TITLE
Apostrophe type mismatch

### ISSUE THREAD

**Issue by fifguy85** [any2cards/worldhaven#30]
Looks like the WAV is only looking for the straight apostrophe type (not the "smart/slanted" one I copied from my Google Doc). 

Here's an example of a page I use to track my campaign's open scenarios (spoiler warning for a smattering of scenario descriptions) that has two instances of Scenario 137's title spelled out with different apostrophes and only one highlights by the viewer: https://boardgamegeek.com/blogpost/145873/available-scenarios-113

I can easily update my text to work with the viewer, so this is an extremely minor bug with an easy workaround. Maybe only worth fixing if there's a simple solution?

**Comment by any2cards** [comment]
This is indeed the case.  WAV is programmed to look for straight apostrophe's (those generated by most keyboards found in the US).  While it would be possible to create aliases for such entries, there is a CRAP ton of them.  I am reluctant to have to do so for everything across five different games/expansions.

**Comment by fifguy85** [comment]
Makes sense. Just wanted to raise it up in case there was an easy solution. :) Those auto-correcting word processors are the real culprits here. ;)
