### ISSUE TITLE
Character tokens

### ISSUE THREAD

**Issue by solomojb** [any2cards/worldhaven#5]
Hello,  

I was just wondering if there are any plans to add character tokens for gh, fc and jotl like there are for cs? 

 I am using worldhaven in https://heisch.github.io/gloomhaven-item-db/ prepping it for fh and adding cs now. (Feel free to add it to the list of product btw)   
 I noticed that cs has the tokens and was wondering if the other games would get them too. (I used custom images for the classes but think the tokens would look better) 

thanks for putting this together. Makes it easy to get all the assets in one project now!

Solomojb

**Comment by solomojb** [comment]
#boob

**Comment by any2cards** [comment]
I am not sure what you mean by "character tokens"?  Do you mean their class tokens?  If so, I do have them and could provide them to you, if you want.  Let me know.

**Comment by solomojb** [comment]
Oh heh.  Yeah the class tokens. (Although looking at the code I see they are called character tokens in cs and class tokens are class specific mechanics?)

That would be great.  I use them for choosing which members are in the party and which solo items are available.

I think that if would make it look better if they look all similar instead of me trying to rip them off the back of the cards. (The ones from jotl and the ones from fh I made look kind of wonky)

Another ask, do you have condition tokens from gh too? I like the look of the cs conditions tokens and would love to change the gh ones to look like that too.



Sent from my iPhone

On May 9, 2022, at 8:32 PM, any2cards ***@***.***> wrote:

﻿

I am not sure what you mean by "character tokens"? Do you mean their class tokens? If so, I do have them and could provide them to you, if you want. Let me know.

**Comment by any2cards** [comment]
After looking at what I have, it came back to me as to why I never put them on GitHub.  Quite frankly, what I have pretty much sucks (compared against other assets).  None the less, I will share a link with you to what I have.  In the meantime, I am going to reach out to my contacts at Cephalofair and see if I can't get the original high res digital versions.  I will let you know.

For now, here is a link to what I do have: https://www.dropbox.com/sh/axu93svw13qfng0/AAAnB8qa9s14COWkS0D7s0I_a?dl=0)

**Comment by solomojb** [comment]
Thank you! That’s much better than what I have. If you come across fc or jotl let me know. (And the envelope x reward too) 

the status icons might be the same as what I have but I’ll see how they look.

**Comment by solomojb** [comment]
Thanks again. That will help!

Sent from my iPhone

On May 9, 2022, at 9:26 PM, any2cards ***@***.***> wrote:

﻿

I added some stuff to the DropBox link for Forgotten Circles and Jaws of the Lion. Pretty much what I currently have. Perhaps you can make use of it.
