### ISSUE TITLE
Monster Ability 715 cut-off element icon

### ISSUE THREAD

**Issue by PrimalZed** [any2cards/worldhaven#6]
https://github.com/any2cards/worldhaven/blob/master/images/monster-ability-cards/gloomhaven/savvas-icestorm/gh-ma-si-8.png

This image has an Air Element icon cut off along the bottom.

(Is this ability supposed to include infusing air, or not?)

**Comment by any2cards** [comment]
No it is not.  This is a mistake on the actual original asset provided for this card.  It should not generate Air.
