### ISSUE TITLE
Asset Viewer not loading

### ISSUE THREAD

**Issue by JimA759** [any2cards/worldhaven#9]
Hi,

Running Chrome (Version 107.0.5304.107 (Official Build) (64-bit)) on Windows 11 Home - on my previous system (Win7pro) Asset Viewer worked just fine. When BGG was loaded and I was viewing messages the card titles would be underlined and I could view the card. However, now with the new system, when in BGG and viewing messages, card names are no longer highlighted and I can't view the card. However, if I open the extension drop down in Chrome and uncheck the box and then recheck the box, everything works normally. If I go to a new message the Asset Viewer is not displaying the underline and I need to 'uncheck and recheck' the box in the dropdown. 

As a side note - I recognize this is a free product and I appreciate the extension - but there really should be a way to report issues without having to create a GitHub account and then figure out how to use it. Not to mention whatever new mailing lists I will be added to. 

thanks, 
JimA

**Comment by any2cards** [comment]
Hmmm ... for some reason, it would seem that Windows 11 Home and Chrome is not storing the settings within local storage (or at least, that is what I am guessing based on the behavior you have stated).  Unfortunately, I do not have access to Windows 11 currently.  Neither of my computers allows me to update to Windows 11 as they do not have TPM.  I am looking at acquiring a new laptop which will run Windows 11 Pro (hopefully sometime soon during Black Friday sales).  Once I have it, I can perform so troubleshooting tests to try and determine what is going on.  Thank you for providing the feedback.

**Comment by JimA759** [comment]
Thanks for the update. Just to be clear, I was forced in to Win11 as my Win7pro machine died and melted after a solid 9 years of use. And I really would have preferred an option for 7. 

 

I still love the extension. 

 

Thanks again,

 

JimA

**Comment by any2cards** [comment]
Jim ... the next time that the viewer is not underlining things, instead of clicking on an off one of the extension choices, try pressing function key F5 to refresh the page.  There have been intermittent issues in the past where pressing F5 (once or multiple times) results in the key words being underlined.  This known issue is due to a timing issue with Chrome as to when the stack sees that the page has completed loading.  I am curious if by pressing F5 your stuff becomes underlined within Windows 11, as this may be the same problem.

**Comment by JimA759** [comment]
I closed out of Chrome and then re-opened. Went to BGG and in the ‘recently viewed’ column the word ‘circles’ is underlined in the game title – Gloomhaven: Forgotten Circles 

 

Opening the page for Forgotten Circles – the description has ‘circles’ and ‘diviner’ and the word ‘suggestion’ (as part of ‘additional suggestions’) all underlined. 

 

Clicking on Forums – there is a list of the first 50 posts – none of the key words are highlighted (underlined) on this page – for examples “rifts / walls / diviner / call of  the nether” – Pressing F5 (multiple times) had no effect – Opening ‘Call of the Nether’ now has the various key words highlighted (underlined) ex: ‘trap / rifts / call of the Nether / diviner’ – Interesting, perhaps the F5 worked after moving from the forum page? Returning to the Forum page, the items not highlighted originally are now highlighted. Let’s try this again. Close Chrome!

 

Same behaviour as before – looking at the Forums list of messages; nothing underlined – not hitting F5 and going to a message results in nothing in the postings is underlined. Now pressing F5 (a couple of times); still no change. Return to Forums; items are now underlined; clicking back on the same message and the key words in the title are underlined but the same words and other key words in the posts are not underlined. Click on the Asset Viewer and uncheck ‘WorldHaven’ and recheck it and everything is now underlined. 

 

Going back to the Forums list – things remain underlined – clicking on a different post – nothing is underlined – tried the F5 and no effect – reset the Asset Viewer and items are underlined. 

 

Hope this helps,

 

JimA

**Comment by any2cards** [comment]
What you have described fits within the family of refresh issues we have seen.  Essentially, the extension works by triggering on a website sending a run_at "document_idle" signal.  Unfortunately, some websites (or pages of sites) either don't consistently honor at document_idle, or they send that it is idle when it really isn't.  The result is that the extension triggers early, or never.  This is why pressing F5 to refresh the page sometimes works.  It's also why unchecking a box and rechecking it can work for the page you are on, but then fails when it goes to a new page.

This extension worked 100% of the time up until about 1 year or so ago when BGG re-designed their website.  It was at that point where things started behaving strangely.  I have reached out to BGG's WebSite Admins to see exactly what they are doing, but they consider that information proprietary, and won't answer my questions.

I will continue to try and find work arounds to solve this overall issue.

**Comment by any2cards** [comment]
A new version of the WAV (2.5.1) has been posted which resolves all of these issues.
